import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/Home.module.css';
import { useGetUserQuery } from '/types/ui/generated';
import { NextPageContext } from 'next';
import auth0 from '/pages/api/utils/auth0';

export default function Home() {
  const results = useGetUserQuery();
  console.log(results.data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Prescott&apos;s Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="api/login" className={styles.card}>
            <h2>Login</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context: NextPageContext) {
  if (context.req && context.res) {
    const session = await auth0.getSession(context.req, context.res);
    console.log(session);
  } else {
  }

  return {
    props: { hello: 'world' },
  };
}
